name: j1_crash_handler
description: A crash handler for the J1 apps.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter
  
  j1_logger:
    git:
      url: https://github.com/J1-Apps/j1_logger.git
      ref: v1.1.0

  firebase_crashlytics: ^2.9.0
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  j1_lints:
    git:
      url: https://github.com/J1-Apps/j1_lints.git
      ref: v1.0.0

  mocktail: ^1.0.4

dependency_overrides:
  plugin_platform_interface: ^2.1.3
